import { IBoard, IGame, IPlayer } from "battleship-types"
import Board from './Board'
import Player from './Player'

class Game implements IGame {
	// Creates a 10x10 board on initialization to use (could be UI generated by size choice)
	public playerBoard: IBoard = new Board()
	public opponentBoard: IBoard = new Board()
	public player: IPlayer
	public opponent: IPlayer

	constructor() {
		// Setup player (could be UI generated)
		const player = new Player('Player', this.playerBoard)
		const opponent = new Player('Opponent', this.opponentBoard)
		this.player = player
		this.opponent = opponent
	}

	public play(): void {
		console.log("Let's play battleship.")
	}
}

export default Game
